apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo
data:
  username: admin
  password: 123456

  ---

  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-demo
  spec:
    selector:
      matchLabels:
        app: nginx-demo
    template:
      metadata:
        labels:
          app: nginx-demo
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80