apiVersion: v1
kind: Secret
metadata:
  name: segredo1
type: Opaque
data:
  usuario: dXN1YXJpby1leGFtcGxv
  senha: c2VuaGEtZXhhbXBsZQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: USUARIO
          valueFrom:
            secretKeyRef:
              name: segredo1
              key: usuario
        - name: SENHA
          valueFrom:
            secretKeyRef:
              name: segredo1
              key: senha

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
