apiVersion: batch/v1
kind: Job
metadata:
  name: echo-command
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: ["echo", "Command completed"]
      restartPolicy: Never
  ttlSecondsAfterFinished: 0