apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 30000
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
