apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meudeployment
spec:
  replicas: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # nao tem downtime da aplicacao, qtde de containers que ira derrubar a cada atualizacao
      maxSurge: 10% # qtde de containers que ira subir a cada atualizacao
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: kubedevio/web-color:blue
        ports:
          - name: http
            containerPort: 80
            protocol: TCP