apiVersion: v1
kind: Pod
metadata: 
  name: myapp-pod1
  labels:
    app: web
    version: blue
spec:
  containers:
    - name: web
      image: kubedevio/web-color:blue
      ports:
        - name: http
          containerPort: 80
          protocol: TCP

  initContainers:
    - name: waitingfordns
      image: busybox:1.28
      command: ['sh', '-c', 'until nslookup myapp-pod1; do echo "waiting for dns"; sleep 2; done']
