apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meudeployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: kubedevio/web-color:green
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata: 
  name: webcolor
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
      nodePort: 30000
      