apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meudeploymentblue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-blue
  template:
    metadata:
      labels:
        app: web-blue
    spec:
      containers:
      - name: web-blue
        image: kubedevio/web-color:blue
        ports:
          - name: http
            containerPort: 80
            protocol: TCP

---

apiVersion: v1
kind: Service
metadata: 
  name: webcolor-blue
spec:
  type: ClusterIP
  selector:
    app: web-blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: http
      