apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meu-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: green.localdev.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webcolor-green
            port:
              number: 8080
  - host: blue.localdev.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webcolor-blue
            port:
              number: 8080