apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-aapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-aapi
    spec:
      containers:
      - name: api
        image: {{ .Values.api.image }}
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "500m"
          limits:
            memory: "64Mi"
            cpu: "500m"
        env:
        - name: Mongo__User
          value: {{ .Values.mongodb.credentials.username }}
        - name: Mongo__Password
          value: {{ .Values.mongodb.credentials.password }}
        - name: Mongo__Host
          value: {{ .Release.Name }}-mongo-service
        - name: Mongo__Database
          value: {{ .Values.mongodb.databaseName }}